#!/bin/bash
# PRUVIQ Social Content Poster
# Part of JEPO Autopilot
# Reads from queue and posts to X (Twitter) and Threads.
#
# Flow:
#   1. Scan queue for pending_approval items
#   2. Auto-approve items that pass validation
#   3. Post to platform API
#   4. Update queue status
#
# Security:
#   - Twitter API credentials from Keychain or .env
#   - Content validation before posting
#   - Rate limiting (max 8 posts/day per platform)
#
# Schedule: every 15 minutes via LaunchAgent
#   (picks up content generated by social-generate.sh)

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/claude-runner.sh"
acquire_lock "post-content"

LOGFILE="$LOG_DIR/post-content.log"
QUEUE_DIR="$HOME/scripts/social/queue"
POSTED_DIR="$HOME/scripts/social/posted"
FAILED_DIR="$HOME/scripts/social/failed"

rotate_log "$LOGFILE"
mkdir -p "$QUEUE_DIR" "$POSTED_DIR" "$FAILED_DIR"

log() {
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ): $1" >> "$LOGFILE"
}

# ─────────────────────────────────────────────────────────────
# Rate limiting: max posts per day per platform
# ─────────────────────────────────────────────────────────────
RATE_DIR="$HOME/scripts/social/rate"
mkdir -p "$RATE_DIR"
MAX_POSTS_PER_DAY=8

check_rate() {
    local platform="$1"
    local today
    today=$(date +%Y-%m-%d)
    local rate_file="$RATE_DIR/${platform}_${today}.count"

    local count=0
    if [[ -f "$rate_file" ]]; then
        count=$(cat "$rate_file" 2>/dev/null || echo "0")
    fi

    if [[ "$count" -ge "$MAX_POSTS_PER_DAY" ]]; then
        return 1  # Rate limited
    fi
    return 0
}

increment_rate() {
    local platform="$1"
    local today
    today=$(date +%Y-%m-%d)
    local rate_file="$RATE_DIR/${platform}_${today}.count"

    local count=0
    if [[ -f "$rate_file" ]]; then
        count=$(cat "$rate_file" 2>/dev/null || echo "0")
    fi
    echo "$((count + 1))" > "$rate_file"

    # Cleanup old rate files (older than 3 days)
    find "$RATE_DIR" -name "*.count" -mtime +3 -delete 2>/dev/null || true
}

# ─────────────────────────────────────────────────────────────
# Content validation (safety check before posting)
# ─────────────────────────────────────────────────────────────
validate_content() {
    local content="$1"
    local platform="$2"

    # Banned words (prevent accidental bot/pruviq identity disclosure)
    # Note: pruviq.com URLs are intentional CTAs — strip URLs before checking
    local content_no_urls
    content_no_urls=$(echo "$content" | sed 's|[a-zA-Z0-9._-]*pruviq\.com[^ ]*||gi')
    local banned_words="자동매매|auto.?trad|our bot|우리 봇|my bot|내 봇|automated|financial advice|NFA|DYOR"
    if echo "$content_no_urls" | grep -qiE "$banned_words"; then
        log "BLOCKED: Content contains banned words"
        return 1
    fi

    # Length check — X: disclaimer 제외 body만 235자 (disclaimer 42자 포함 시 277자 ≤ 280)
    # quality-checker.py와 동일 기준 유지
    if [[ "$platform" == "x" ]]; then
        local DISCLAIMER="Simulated backtest. Not financial advice."
        local content_body="${content//$'\n'$DISCLAIMER/}"
        content_body="${content_body//$DISCLAIMER/}"
        if [[ ${#content_body} -gt 237 ]]; then
            log "BLOCKED: X content body exceeds 237 chars (${#content_body}, total=${#content})"
            return 1
        fi
    fi

    # Empty/too short
    if [[ ${#content} -lt 20 ]]; then
        log "BLOCKED: Content too short (${#content} chars)"
        return 1
    fi

    return 0
}

# ─────────────────────────────────────────────────────────────
# Post to X (Twitter) via v2 API
# ─────────────────────────────────────────────────────────────
post_to_x() {
    local content="$1"
    local chart="$2"  # optional image path

    # Load credentials
    local API_KEY
    local API_SECRET
    local ACCESS_TOKEN
    local ACCESS_SECRET

    # Try Keychain first (service names: x-api-key, x-api-secret, x-access-token, x-access-secret, account: pruviq)
    API_KEY=$(security find-generic-password -a "pruviq" -s "x-api-key" -w 2>/dev/null) || true
    API_SECRET=$(security find-generic-password -a "pruviq" -s "x-api-secret" -w 2>/dev/null) || true
    ACCESS_TOKEN=$(security find-generic-password -a "pruviq" -s "x-access-token" -w 2>/dev/null) || true
    ACCESS_SECRET=$(security find-generic-password -a "pruviq" -s "x-access-secret" -w 2>/dev/null) || true

    # Fallback to .env file
    if [[ -z "$API_KEY" ]]; then
        if [[ -f "$HOME/scripts/.env.x" ]]; then
            source "${HOME}/.secrets.env"
            API_KEY="${X_API_KEY:-}"
            API_SECRET="${X_API_SECRET:-}"
            ACCESS_TOKEN="${X_ACCESS_TOKEN:-}"
            ACCESS_SECRET="${X_ACCESS_TOKEN_SECRET:-}"
        fi
    fi

    if [[ -z "$API_KEY" || -z "$ACCESS_TOKEN" ]]; then
        log "X: No credentials found (Keychain, .env.x, or .env.twitter)"
        return 2  # No credentials (skip, don't fail)
    fi

    # Post using Python (OAuth1 via requests-oauthlib)
    local result
    result=$(TWITTER_API_KEY="$API_KEY" \
             TWITTER_API_SECRET="$API_SECRET" \
             TWITTER_ACCESS_TOKEN="$ACCESS_TOKEN" \
             TWITTER_ACCESS_SECRET="$ACCESS_SECRET" \
             CHART_PATH="${chart:-}" \
             python3 -c "
import os, json, sys

try:
    from requests_oauthlib import OAuth1Session
except ImportError:
    print(json.dumps({'error': 'requests-oauthlib not installed'}))
    sys.exit(1)

api_key = os.environ['TWITTER_API_KEY']
api_secret = os.environ['TWITTER_API_SECRET']
access_token = os.environ['TWITTER_ACCESS_TOKEN']
access_secret = os.environ['TWITTER_ACCESS_SECRET']
chart_path = os.environ.get('CHART_PATH', '')

content = sys.stdin.read().strip()

oauth = OAuth1Session(api_key, api_secret, access_token, access_secret)

media_id = None
if chart_path and os.path.isfile(chart_path):
    # Upload media first
    upload_url = 'https://upload.twitter.com/1.1/media/upload.json'
    with open(chart_path, 'rb') as f:
        resp = oauth.post(upload_url, files={'media': f})
    if resp.status_code == 200:
        media_id = resp.json().get('media_id_string')

# Post tweet
payload = {'text': content}
if media_id:
    payload['media'] = {'media_ids': [media_id]}

resp = oauth.post('https://api.twitter.com/2/tweets', json=payload)
result = {'status': resp.status_code}
try:
    result['data'] = resp.json()
except:
    result['body'] = resp.text[:200]
print(json.dumps(result))
" <<< "$content" 2>&1)

    local status
    status=$(echo "$result" | python3 -c "import sys,json; print(json.load(sys.stdin).get('status',0))" 2>/dev/null || echo "0")

    if [[ "$status" == "201" ]]; then
        local tweet_id
        tweet_id=$(echo "$result" | python3 -c "import sys,json; print(json.load(sys.stdin).get('data',{}).get('data',{}).get('id',''))" 2>/dev/null || echo "")
        log "X: Posted successfully (tweet_id=$tweet_id)"
        return 0
    else
        log "X: Post failed (status=$status): ${result:0:300}"
        return 1
    fi
}

# ─────────────────────────────────────────────────────────────
# Post to Threads via Graph API
# ─────────────────────────────────────────────────────────────
post_to_threads() {
    local content="$1"
    local chart="$2"  # optional image path (not yet supported for Threads)

    local ACCESS_TOKEN
    ACCESS_TOKEN=$(security find-generic-password -a "pruviq" -s "threads-access-token" -w 2>/dev/null) || true

    if [[ -z "$ACCESS_TOKEN" ]]; then
        if [[ -f "$HOME/scripts/social/.env.threads" ]]; then
            source "${HOME}/.secrets.env"
            ACCESS_TOKEN="${THREADS_ACCESS_TOKEN:-}"
        fi
    fi

    if [[ -z "$ACCESS_TOKEN" ]]; then
        log "Threads: No credentials found"
        return 2
    fi

    # Load user ID from .env.threads (required for Threads Graph API — /me is rejected with 400)
    local THREADS_USER_ID=""
    if [[ -f "$HOME/scripts/social/.env.threads" ]]; then
        THREADS_USER_ID=$(grep "THREADS_USER_ID" "$HOME/scripts/social/.env.threads" | cut -d= -f2 | tr -d '"' | tr -d "'")
    fi
    if [[ -z "$THREADS_USER_ID" ]]; then
        log "Threads: No THREADS_USER_ID found in .env.threads"
        return 2
    fi

    # Threads API: Create media container → Publish
    local result
    result=$(THREADS_TOKEN="$ACCESS_TOKEN" THREADS_USER_ID="$THREADS_USER_ID" python3 -c "
import os, json, sys, urllib.request, urllib.parse

token = os.environ['THREADS_TOKEN']
user_id = os.environ['THREADS_USER_ID']
content = sys.stdin.read().strip()

# Step 1: Create media container (must use user_id, not 'me' — /me returns 400)
params = urllib.parse.urlencode({
    'media_type': 'TEXT',
    'text': content,
    'access_token': token,
})
url = f'https://graph.threads.net/v1.0/{user_id}/threads?{params}'
req = urllib.request.Request(url, method='POST')
try:
    with urllib.request.urlopen(req, timeout=15) as resp:
        container = json.loads(resp.read().decode())
except Exception as e:
    print(json.dumps({'error': str(e)}))
    sys.exit(1)

container_id = container.get('id')
if not container_id:
    print(json.dumps({'error': 'No container ID', 'response': container}))
    sys.exit(1)

# Step 2: Publish
import time
time.sleep(2)  # Threads needs brief delay
pub_params = urllib.parse.urlencode({
    'creation_id': container_id,
    'access_token': token,
})
pub_url = f'https://graph.threads.net/v1.0/{user_id}/threads_publish?{pub_params}'
req2 = urllib.request.Request(pub_url, method='POST')
try:
    with urllib.request.urlopen(req2, timeout=15) as resp:
        result = json.loads(resp.read().decode())
except Exception as e:
    print(json.dumps({'error': str(e)}))
    sys.exit(1)

print(json.dumps({'success': True, 'id': result.get('id', '')}))
" <<< "$content" 2>&1)

    if echo "$result" | python3 -c "import sys,json; assert json.load(sys.stdin).get('success')" 2>/dev/null; then
        local post_id
        post_id=$(echo "$result" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "")
        log "Threads: Posted successfully (id=$post_id)"
        return 0
    else
        log "Threads: Post failed: ${result:0:300}"
        return 1
    fi
}

# ─────────────────────────────────────────────────────────────
# Post to Instagram via Graph API
# ─────────────────────────────────────────────────────────────
post_to_instagram() {
    local content="$1"
    local image="$2"  # REQUIRED for Instagram

    if [[ -z "$image" || ! -f "$image" ]]; then
        log "Instagram: No image provided (required)"
        return 1
    fi

    local ACCESS_TOKEN
    local USER_ID
    ACCESS_TOKEN=$(get_secret "instagram-access-token" 2>/dev/null) || true
    USER_ID=$(get_secret "instagram-user-id" 2>/dev/null) || true

    if [[ -z "$ACCESS_TOKEN" ]]; then
        source "${HOME}/.secrets.env"
            ACCESS_TOKEN="${INSTAGRAM_ACCESS_TOKEN:-}"
            USER_ID="${INSTAGRAM_USER_ID:-}"
    fi

    if [[ -z "$ACCESS_TOKEN" || -z "$USER_ID" ]]; then
        log "Instagram: No credentials found"
        return 2
    fi

    # Instagram Graph API requires a PUBLIC image URL.
    # Upload to Cloudflare R2 first, then use the URL.
    local image_url
    image_url=$(upload_image_to_r2 "$image")

    if [[ -z "$image_url" || "$image_url" == "null" ]]; then
        log "Instagram: Failed to upload image to R2"
        return 1
    fi

    log "Instagram: Image uploaded to $image_url"

    # Post using Python (Instagram Graph API)
    local result
    result=$(IG_TOKEN="$ACCESS_TOKEN" IG_USER_ID="$USER_ID" IG_IMAGE_URL="$image_url" \
        python3 -c "
import os, json, sys, urllib.request, urllib.parse, time

token = os.environ['IG_TOKEN']
user_id = os.environ['IG_USER_ID']
image_url = os.environ['IG_IMAGE_URL']
caption = sys.stdin.read().strip()

# Step 1: Create media container
params = urllib.parse.urlencode({
    'image_url': image_url,
    'caption': caption,
    'access_token': token,
})
url = f'https://graph.facebook.com/v21.0/{user_id}/media?{params}'
req = urllib.request.Request(url, method='POST')
try:
    with urllib.request.urlopen(req, timeout=30) as resp:
        container = json.loads(resp.read().decode())
except Exception as e:
    print(json.dumps({'error': str(e)}))
    sys.exit(1)

container_id = container.get('id')
if not container_id:
    print(json.dumps({'error': 'No container ID', 'response': container}))
    sys.exit(1)

# Step 2: Wait for container to be ready (Instagram needs processing time)
time.sleep(5)

# Step 3: Publish
pub_params = urllib.parse.urlencode({
    'creation_id': container_id,
    'access_token': token,
})
pub_url = f'https://graph.facebook.com/v21.0/{user_id}/media_publish?{pub_params}'
req2 = urllib.request.Request(pub_url, method='POST')
try:
    with urllib.request.urlopen(req2, timeout=30) as resp:
        result = json.loads(resp.read().decode())
except Exception as e:
    print(json.dumps({'error': str(e)}))
    sys.exit(1)

print(json.dumps({'success': True, 'id': result.get('id', '')}))
" <<< "$content" 2>&1)

    if echo "$result" | python3 -c "import sys,json; assert json.load(sys.stdin).get('success')" 2>/dev/null; then
        local post_id
        post_id=$(echo "$result" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "")
        log "Instagram: Posted successfully (id=$post_id)"
        return 0
    else
        log "Instagram: Post failed: ${result:0:300}"
        return 1
    fi
}

# ─────────────────────────────────────────────────────────────
# Upload image to Cloudflare R2 (for Instagram public URL)
# ─────────────────────────────────────────────────────────────
upload_image_to_r2() {
    local image_path="$1"
    local filename
    filename=$(basename "$image_path")

    # R2 credentials from .env
    local R2_ACCOUNT_ID R2_ACCESS_KEY R2_SECRET_KEY R2_BUCKET R2_PUBLIC_URL
    if [[ -f "$HOME/scripts/social/.env.r2" ]]; then
        source "$HOME/scripts/social/.env.r2"
    fi

    if [[ -z "$R2_ACCOUNT_ID" || -z "$R2_ACCESS_KEY" ]]; then
        # Fallback: use wrangler r2 (if available)
        local r2_key="social-images/${filename}"
        if command -v wrangler &>/dev/null; then
            wrangler r2 object put "pruviq-social/${r2_key}" \
                --file "$image_path" \
                --content-type "image/png" 2>/dev/null
            if [[ $? -eq 0 ]]; then
                echo "${R2_PUBLIC_URL:-https://social-assets.pruviq.com}/${r2_key}"
                return 0
            fi
        fi

        # Fallback 2: Use API server to serve image
        # Upload via SCP to a public directory on the API server
        local api_host="167.172.81.145"
        local remote_dir="/opt/autotrader/static/social"
        ssh -p 2222 -o ConnectTimeout=10 root@"$api_host" "mkdir -p $remote_dir" 2>/dev/null
        scp -P 2222 -o ConnectTimeout=10 "$image_path" "root@${api_host}:${remote_dir}/${filename}" 2>/dev/null
        if [[ $? -eq 0 ]]; then
            echo "https://api.pruviq.com/static/social/${filename}"
            return 0
        fi

        log "Instagram: No R2 credentials and wrangler/SCP fallback failed"
        return 1
    fi

    # AWS S3-compatible upload to R2
    python3 -c "
import os, sys, hashlib, hmac, datetime, urllib.request

account_id = os.environ.get('R2_ACCOUNT_ID', '')
access_key = os.environ.get('R2_ACCESS_KEY', '')
secret_key = os.environ.get('R2_SECRET_KEY', '')
bucket = os.environ.get('R2_BUCKET', 'pruviq-social')
public_url = os.environ.get('R2_PUBLIC_URL', 'https://social-assets.pruviq.com')
filename = '$filename'
filepath = '$image_path'

# Simple PUT using presigned URL approach
key = f'social-images/{filename}'

with open(filepath, 'rb') as f:
    data = f.read()

# Direct R2 API upload (simplified)
endpoint = f'https://{account_id}.r2.cloudflarestorage.com/{bucket}/{key}'

import subprocess
result = subprocess.run([
    'curl', '-s', '-X', 'PUT', endpoint,
    '-H', f'X-Custom-Auth-Key: {access_key}',
    '-H', 'Content-Type: image/png',
    '--data-binary', f'@{filepath}',
    '-w', '%{http_code}',
    '-o', '/dev/null',
], capture_output=True, text=True, timeout=30)

if result.stdout.strip() in ('200', '201'):
    print(f'{public_url}/{key}')
else:
    print('')
" 2>/dev/null
}

# ─────────────────────────────────────────────────────────────
# Main: Process Queue
# ─────────────────────────────────────────────────────────────
# Date gate: posting enabled from this date onwards (UTC)
POSTING_START_DATE="2026-03-16"
if [[ "$(date -u +%Y-%m-%d)" < "$POSTING_START_DATE" ]]; then
    log "HOLD: Posting paused until $POSTING_START_DATE (today=$(date -u +%Y-%m-%d))"
    exit 0
fi

# ─── Cleanup: remove failed/ items older than 30 days ───
if [[ -d "$FAILED_DIR" ]]; then
    cleaned_count=0
    for failed_file in "$FAILED_DIR"/*.json; do
        [[ -f "$failed_file" ]] || continue
        file_age=$(( $(date +%s) - $(stat -f%m "$failed_file" 2>/dev/null || echo 0) ))
        if [[ $file_age -gt 2592000 ]]; then  # 30 days
            rm -f "$failed_file"
            cleaned_count=$((cleaned_count + 1))
        fi
    done
    [[ $cleaned_count -gt 0 ]] && log "Cleaned $cleaned_count expired failed items (>30d)"
fi

log "Scanning queue..."
PROCESSED=0

for queue_file in "$QUEUE_DIR"/*.json; do
    [[ -f "$queue_file" ]] || continue

    # Read queue item
    local_status=$(python3 -c "import json; d=json.load(open('$queue_file')); print(d.get('status',''))" 2>/dev/null)

    # Auto-expire pending_approval items older than 24 hours
    if [[ "$local_status" == "pending_approval" ]]; then
        file_age=$(( $(date +%s) - $(stat -f%m "$queue_file" 2>/dev/null || echo 0) ))
        if [[ $file_age -gt 86400 ]]; then
            python3 -c "
import json
with open('$queue_file') as f: d = json.load(f)
d['status'] = 'expired'
with open('$queue_file', 'w') as f: json.dump(d, f, ensure_ascii=False, indent=2)
" 2>/dev/null
            mv "$queue_file" "$FAILED_DIR/" 2>/dev/null || true
            log "EXPIRED: $(basename $queue_file) (pending >24h)"
        fi
        continue
    fi

    # Only post explicitly approved items — pending_approval waits for Telegram button response
    if [[ "$local_status" != "approved" ]]; then
        continue
    fi

    platform=$(python3 -c "import json; d=json.load(open('$queue_file')); print(d.get('platform',''))" 2>/dev/null)
    content=$(python3 -c "import json; d=json.load(open('$queue_file')); print(d.get('content',''))" 2>/dev/null)
    chart=$(python3 -c "import json; d=json.load(open('$queue_file')); print(d.get('chart',''))" 2>/dev/null)

    if [[ -z "$platform" || -z "$content" ]]; then
        log "Invalid queue file: $queue_file"
        mv "$queue_file" "$FAILED_DIR/" 2>/dev/null || true
        continue
    fi

    # Rate check
    if ! check_rate "$platform"; then
        log "$platform: Rate limited ($MAX_POSTS_PER_DAY/day), skipping"
        continue
    fi

    # Validate content
    if ! validate_content "$content" "$platform"; then
        # Update status to failed
        python3 -c "
import json
with open('$queue_file') as f: d = json.load(f)
d['status'] = 'validation_failed'
with open('$queue_file', 'w') as f: json.dump(d, f, ensure_ascii=False, indent=2)
" 2>/dev/null
        mv "$queue_file" "$FAILED_DIR/" 2>/dev/null || true
        continue
    fi

    # Post!
    POST_RESULT=1
    case "$platform" in
        x)
            post_to_x "$content" "$chart"
            POST_RESULT=$?
            ;;
        threads)
            post_to_threads "$content" "$chart"
            POST_RESULT=$?
            ;;
        instagram)
            post_to_instagram "$content" "$chart"
            POST_RESULT=$?
            ;;
        *)
            log "Unknown platform: $platform"
            POST_RESULT=1
            ;;
    esac

    # Update status
    if [[ $POST_RESULT -eq 0 ]]; then
        python3 -c "
import json
from datetime import datetime, timezone
with open('$queue_file') as f: d = json.load(f)
d['status'] = 'posted'
d['posted_at'] = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
with open('$queue_file', 'w') as f: json.dump(d, f, ensure_ascii=False, indent=2)
" 2>/dev/null
        mv "$queue_file" "$POSTED_DIR/" 2>/dev/null || true
        increment_rate "$platform"
        PROCESSED=$((PROCESSED + 1))
    elif [[ $POST_RESULT -eq 2 ]]; then
        # No credentials — leave in queue for later
        log "$platform: No credentials, leaving in queue"
    else
        python3 -c "
import json
from datetime import datetime, timezone
with open('$queue_file') as f: d = json.load(f)
d['status'] = 'post_failed'
d['failed_at'] = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
with open('$queue_file', 'w') as f: json.dump(d, f, ensure_ascii=False, indent=2)
" 2>/dev/null
        mv "$queue_file" "$FAILED_DIR/" 2>/dev/null || true
    fi
done

# Cleanup old posted/failed (keep 7 days)
find "$POSTED_DIR" -name "*.json" -mtime +7 -delete 2>/dev/null || true
find "$FAILED_DIR" -name "*.json" -mtime +7 -delete 2>/dev/null || true

log "Processed: $PROCESSED posts"

if [[ $PROCESSED -gt 0 ]]; then
    send_telegram "<b>[Social Poster]</b> Posted $PROCESSED items"
fi
